apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "guacamole.fullname" . }}-guacamole
  labels:
{{ include "guacamole.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "guacamole.name" . }}-guacamole
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "guacamole.name" . }}-guacamole
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.guacamole.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      initContainers:
        - name: create-init-db
          image: "{{ .Values.guacamole.image.repository }}:{{ tpl .Values.guacamole.image.tag . }}"
          imagePullPolicy: {{ .Values.guacamole.image.pullPolicy }}
          envFrom:
            - secretRef:
                name: {{ include "guacamole.fullname" . }}
          resources:
            {{- toYaml .Values.guacamole.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.guacamole.securityContext | nindent 12 }}
          volumeMounts:
            - name: initdb
              mountPath: /data
          command: ["/bin/sh"]
          args:
            - -c
            - |
              /opt/guacamole/bin/initdb.sh --postgresql > /data/initdb.sql
        - name: loaddb
          image: "{{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}"
          imagePullPolicy: {{ .Values.postgres.image.pullPolicy }}
          envFrom:
            - secretRef:
                name: {{ include "guacamole.fullname" . }}
          resources:
            {{- toYaml .Values.postgres.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.guacamole.securityContext | nindent 12 }}
          volumeMounts:
            - name: initdb
              mountPath: /data
          command: ["/bin/sh"]
          args:
            - -c
            - |
              echo "Waiting for postgres to come online"
              while ! nc -z $POSTGRESQL_HOSTNAME $POSTGRESQL_PORT; do
                sleep 1
              done
              export PGPASSWORD=$POSTGRESQL_PASSWORD
              psql -h $POSTGRESQL_HOSTNAME -d $POSTGRESQL_DATABASE -U $POSTGRESQL_USER -p $POSTGRESQL_PORT "sslmode=$POSTGRESQL_SSL_MODE" -a -w -f /data/initdb.sql
      {{- if .Values.certificateTrust.chain }}
        - name: {{ .Release.Name }}-init-jks
          image: "{{ .Values.guacamole.image.repository }}:{{ tpl .Values.guacamole.image.tag . }}"
          command: ['sh', '-c', '/load/certimport.sh']
          volumeMounts:
            - name: {{ include "guacamole.fullname" . }}-certchain
              mountPath: /load/
          securityContext:
            {{- toYaml .Values.guacamole.securityContext | nindent 12 }}
        {{ include "truststore.volumeMounts" . | indent 4 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.guacamole.image.repository }}:{{ tpl .Values.guacamole.image.tag . }}"
          imagePullPolicy: {{ .Values.guacamole.image.pullPolicy }}
          envFrom:
            - secretRef:
                name: {{ include "guacamole.fullname" . }}
          ports:
            - name: http
              containerPort: {{ .Values.guacamole.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.guacamole.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.guacamole.securityContext | nindent 12 }}
          automountServiceAccountToken: false
      {{- if .Values.certificateTrust.chain }}
          volumeMounts:
          {{- include "truststore.volumeMounts" . | nindent 12 -}}
      {{- end }}
      volumes:
        - name: initdb
          emptyDir: {}
      {{- if .Values.certificateTrust.chain }}
      {{- include "truststore.volumes" . | nindent 8 }}
      {{- end }}