{{- define "postgres.hostname" -}}
{{- if .Values.postgres.enabled -}}
{{- printf "%s-postgres" (include "guacamole.fullname" .) -}}
{{- else -}}
{{- .Values.postgres.hostname -}}
{{- end -}}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "guacamole.fullname" . }}
  labels:
{{ include "guacamole.labels" . | indent 4 }}
type: Opaque
data:
  GUACD_HOSTNAME: {{ printf "%s-%s" (include "guacamole.fullname" .) "guacd" | b64enc | quote }}
  GUACD_PORT: {{ "4822" | b64enc | quote }}
  POSTGRESQL_HOSTNAME: {{ include "postgres.hostname" . | b64enc | quote }}
  POSTGRESQL_PORT: {{ .Values.postgres.service.port | b64enc | quote }}
  POSTGRESQL_DATABASE: {{ .Values.postgres.database | b64enc | quote }}
  POSTGRESQL_USER: {{ .Values.postgres.user | b64enc | quote }}
  POSTGRESQL_PASSWORD: {{ .Values.postgres.password | b64enc | quote }}
  {{- if .Values.cacerts.enabled }}
  JAVA_TOOL_OPTIONS: {{ printf "-Djavax.net.ssl.trustStore=/cacerts/cacerts.jks -Djavax.net.ssl.trustStorePassword=changeit" | b64enc | quote }}
  {{- end }}
  {{- range $key, $value := .Values.guacamole.settings }}
  {{ regexReplaceAll "\\W+" (upper $key) "_" }}: {{ $value | b64enc | quote }}
  {{- end }}
