{{- $fullName := include "guacamole.fullname" . -}}
{{- define "postgres.hostname" -}}
{{- if .Values.postgres.enabled -}}
{{- $fullName := include "guacamole.fullname" . -}}
{{- printf "%s-postgres" $fullName -}}
{{- else -}}
{{- .Values.postgres.hostname -}}
{{- end -}}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.guacamole.name }}-secret
  namespace: {{ .Release.Namespace | quote }}
  labels:
{{ include "guacamole.labels" . | indent 4 }}
type: Opaque
data:
  GUACD_HOSTNAME: {{ printf "%s-guacd" $fullName | b64enc | quote }}
  GUACD_PORT: {{ .Values.guacd.service.port | toString | b64enc | quote }}
  POSTGRESQL_HOSTNAME: {{ include "postgres.hostname" . | b64enc | quote }}
  POSTGRESQL_PORT: {{ .Values.postgres.service.port | b64enc | quote }}
  POSTGRESQL_DATABASE: {{ .Values.postgres.database | b64enc | quote }}
  POSTGRESQL_USERNAME: {{ .Values.postgres.user | b64enc | quote }}
  POSTGRESQL_USER: {{ .Values.postgres.user | b64enc | quote }}
  POSTGRESQL_PASSWORD: {{ .Values.postgres.password | b64enc | quote }}
  {{- if .Values.certificateTrust.chain }}
  JAVA_TOOL_OPTIONS: {{ (include "truststore.javaOpts" .) | b64enc | quote }}
  {{- end }}
  {{- range $key, $value := .Values.guacamole.settings }}
  {{ regexReplaceAll "\\W+" (upper $key) "_" }}: {{ $value | b64enc | quote }}
  {{- end }}
