{{- $fullName := include "guacamole.fullname" . -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}-guacamole
  namespace: {{ .Release.Namespace | quote }}
  labels:
{{ include "guacamole.labels" . | indent 4 }}
spec:
  type: {{ .Values.guacamole.service.type }}
  ports:
    - port: {{ .Values.guacamole.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "guacamole.name" . }}-guacamole
    app.kubernetes.io/instance: {{ .Release.Name }}
