apiVersion: v1
appVersion: 1.5.5
description:
  Apache Guacamole is a clientless remote desktop gateway. It supports
  standard protocols like VNC, RDP, and SSH.
  This version of the helm chart includes both OpenID and custom CA root
  certificate capabilities.
icon: http://guacamole.apache.org/images/guacamole-logo-64.png
name: guacamole-helm
sources:
  - http://guacamole.apache.org/
version: 1.5.5
dependencies:
  - name: ingress-nginx # https://artifacthub.io/packages/helm/ingress-nginx/ingress-nginx
    version: ~4.8.3
    repository: "https://kubernetes.github.io/ingress-nginx"
    condition: ingress.enabled
