{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "guacamole.fullname" . }}-pvc
  labels:
  {{- include "guacamole.labels" . | nindent 4 }}
spec:
{{- if .Values.postgres.pvc.storageClassName }}
  storageClassName: {{ .Values.postgres.pvc.storageClassName | quote }}
{{- end }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgres.pvc.storageRequest | quote }}
{{- if .Values.postgres.pvc.selector }}
  selector:
    {{- toYaml .Values.postgres.pvc.selector | nindent 4 }}
{{- end }}
{{- end }}