apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.guacd.name }}-svc
  labels:
{{ include "guacamole.labels" . | indent 4 }}
spec:
  type: {{ .Values.guacd.service.type }}
  ports:
    - port: {{ .Values.guacd.service.port }}
      targetPort: guacd
      protocol: TCP
      name: guacd
  selector:
    app.kubernetes.io/name: {{ include "guacamole.name" . }}-guacd
    app.kubernetes.io/instance: {{ .Release.Name }}
